# Loads default set of integrations. Do not remove.
default_config:

homeassistant: !include homeassistant.yaml

logger:
  default: warning

ffmpeg:
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
lovelace:
  mode: storage
  dashboards: 
    dashboard-documentacion:
      mode: yaml
      title: Documentacion
      icon: mdi:file-document-multiple
      show_in_sidebar: true
      filename: documentacion.yaml
